# ==============================================================================
# REDIS CONFIGURATION FILE
# ==============================================================================

# --- 1. NETWORK SETTINGS ---
# Mendengarkan koneksi dari semua antarmuka jaringan
bind 0.0.0.0
port 6379

# Protected mode diaktifkan sebagai lapisan keamanan dasar
protected-mode yes

# Menutup koneksi klien yang diam (idle) setelah 300 detik (5 menit)
timeout 300

# Mengirim paket TCP ACK setiap 300 detik untuk mendeteksi koneksi terputus
tcp-keepalive 300


# --- 2. GENERAL & ENVIRONMENT ---
# 'no' wajib untuk penggunaan di dalam kontainer Docker / Kubernetes
daemonize no

# Menentukan lokasi direktori penyimpanan file data (RDB & AOF)
dir /data


# --- 3. LOGGING ---
# Tingkat detail log (options: debug, verbose, notice, warning)
loglevel notice
# loglevel debug
# loglevel verbose
# loglevel warning

# Mengarahkan log ke stdout (layar terminal/docker log)
logfile ""
# logfile "/var/log/redis/redis-server.log"


# --- 4. MEMORY MANAGEMENT ---
# Batas maksimal penggunaan memori RAM
maxmemory 200mb

# Kebijakan penghapusan data saat memori penuh
maxmemory-policy allkeys-lru
# maxmemory-policy noeviction
# maxmemory-policy allkeys-lfu
# maxmemory-policy allkeys-random
# maxmemory-policy volatile-lfu
# maxmemory-policy volatile-lru
# maxmemory-policy volatile-random

# Jumlah sampel acak yang diperiksa untuk kalkulasi LRU/LFU
maxmemory-samples 5


# --- 5. USER MANAGEMENT & SECURITY (ACL) ---
# Mematikan user 'default' (praktek keamanan terbaik untuk ACL)
user default off
# user default on >Sudo@1234 ~* +@all

# User khusus ACL
user admin on >Admin@1234 ~* +@all
user user on >User@1234 ~* -@all +@read


# --- 6. PERSISTENCE (RDB - SNAPSHOT) ---
# Jadwal otomatis pembuatan snapshot RDB ke disk
save 900 1
save 300 10
save 60 10000

# Nama file snapshot RDB
dbfilename dump.rdb

# Mengompresi file RDB menggunakan LZF (ringan & menghemat ruang disk)
rdbcompression yes


# --- 7. PERSISTENCE (AOF - APPEND ONLY FILE) ---
# Mengaktifkan mode AOF untuk mencegah kehilangan data (durability tinggi)
appendonly yes

# Nama file log AOF
appendfilename "appendonly.aof"

# Frekuensi sinkronisasi data AOF ke disk
# 'everysec' adalah rekomendasi terbaik (seimbang antara performa dan keamanan)
appendfsync everysec
# appendfsync always
# appendfsync no

# Mencegah operasi fsync saat proses rewrite berlangsung agar IO disk tidak leher botol (bottleneck)
no-appendfsync-on-rewrite yes

# Mekanisme AOF Rewrite Otomatis (Memadatkan ukuran file AOF agar tidak membengkak)
# Trigger rewrite jika ukuran file tumbuh 100% dari ukuran setelah rewrite terakhir...
auto-aof-rewrite-percentage 100
# ...dan ukuran minimal file AOF sudah mencapai 64 MB
auto-aof-rewrite-min-size 64mb

# Mengaktifkan Hybrid Persistence (Menggabungkan kecepatan RDB & ketelitian AOF)
aof-use-rdb-preamble yes